version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-docker-app:
    build: 
        context: .
        args:
          - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_USER=nodedb
      - MONGO_PASSWORD=1234
      - SESSION_SECRET=secret
    command: node index.js
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nodedb
      - MONGO_INITDB_ROOT_PASSWORD=1234