version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    
  node-docker-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    #ports:
    #  - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nodedb
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - PORT=6379


volumes:
  mongo-db: