version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-docker-app:
    build: 
        context: .
        args:
          - NODE_ENV=production
    environment:
      - NODE_ENV=production

    command: npm start